import type { Metadata } from "next";
import { Poppins } from 'next/font/google';//font
// import { Inter } from "next/font/google";
import '@/app/ui/reset.css';
import '@/app/ui/global.css';
import Navbar from '@/app/ui/Navbar';



//font
// export const inter = Inter({
//   subsets: ['latin'], // Required: specifies character set (latin is sufficient for English)
//   variable: '--font-inter', // CSS custom property for Tailwind integration
//   display: 'swap', // Prevents layout shift by using fallback font until loaded
// });

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'], // Specify weights you need
  style: ['normal', 'italic'], // Optional: Include italic if needed
  subsets: ['latin'], // Specify subsets (e.g., 'latin', 'latin-ext')
  display: 'swap', // Font-display strategy for better UX (swap is recommended)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >
         <Navbar />
        {children}
      </body>
    </html>
  );
}


